apiVersion: v1 # config and secret must exist before Deployment
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # default for secret data
data: # can have third party app to encode the credentials too.
  mongo-user: bW9uZ291c2Vy # base64 for "mongouser"
  mongo-password: bW9uZ29wYXNzd29yZA== # base64 for "mongopassword"